data_global

loop_
_rlnTomoName
_rlnTomoTiltSeriesName
_rlnTomoImportCtfFindFile
_rlnTomoImportImodDir
_rlnTomoImportFractionalDose
_rlnTomoImportOffsetX
_rlnTomoImportOffsetY
_rlnTomoImportOffsetZ
_rlnTomoImportOrderList
